### PR TITLE
Creating Footer

### PR DESCRIPTION
**Pull request by Ferdinand-Ogama**
Hello, 

Thanks for giving me this chance. 
I'd like to know what I should improve. 

Best.

### CODE REVIEW

**Review by eduardconstantin — CHANGES_REQUESTED** [review]
This looks pretty good, just some minor changes.

**Comment by Ferdinand-Ogama** [comment]
Working on the changes.

**Comment by Ferdinand-Ogama** [comment]
Updated per the requested changes.

**Review by eduardconstantin — APPROVED** [review]
Thank you for your contribution!

**Pull request merged**
